# Generated by Django 4.2.4 on 2024-03-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('post', models.CharField(default='', max_length=500)),
                ('thumbnail', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
