# Generated by Django 4.2.4 on 2024-03-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
