# Generated by Django 4.2.4 on 2024-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(choices=[('Paris', 'Paris'), ('New York', 'New York'), ('Tokyo', 'Tokyo'), ('London', 'London'), ('Sydney', 'Sydney')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
